#3강 데이터의 입력과 저장

#작업디렉토리 설정(setwd) 및 확인 (getwd())

In [6]:
x <- c(1,2,3,4,5)
y <- c(10,20,30,40,50)
dat <- cbind(x,y)
dat

x y 
[1,] 1 10
[2,] 2 20
[3,] 3 30
[4,] 4 40
[5,] 5 50

In [9]:
w1 <- scan() #방을 만들어서 scan 쓴 다음에 입력 끝나면 공백에서 엔터 
23
4
5
6
7


[1] 23

[1] 4

[1] 5

[1] 6

[1] 7

#edit() 함수 이용한 입력 (창을 새로 띄워서 입력)

#데이터 저장

sink() 시작 시 저장할 파일명을 지정하고 원하는 함수를 실행시킨 뒤 종료시 sink()로 마감. write.csv(dat, '파일명.csv', quote=T, rownmaes=T 등의 옵션 가능) write.table() 도 비슷한데 공백으로 구분해주고 sep=",' 로 주면 csv 와 비슷해 진다 

read.csv ('파일명', header=T(이거 디폴트옵션) 변수명이 없는 첫번째 칼럼은 x라는 변수명 자동 할당됨 (그래서 미리 csv 파일 전처리해야함)stringsAsFactors=F 라는 옵션을 주면 문자 변수가 factor 변수로 인식되지 않도록 지정 read.table 은 header=F 가 디폴트라는 점이 read.csv 와 다르다. na.strings='aa' 하면 aa를 결측치로 인식. 

#객체 확인 및 삭제
ls() 모든 객체 확인, rm(list=ls()) 모든 객체 삭제  

#4강 데이터 구조 (1) - 벡터, 행렬

In [1]:
v1 <- c("1", "Korea", "National", "Open", "University")
length(v1) #벡터의 크기 출력

[1] 5

In [3]:
seq (from=3, to=7, by=1) #from=시작값, to=종료값, by=증가분
seq (3,7,1) #생략 시 시작, 종료, 증가분 순서로 인식

[1] 3 4 5 6 7

[1] 3 4 5 6 7

In [4]:
seq(3,7, length=3) #length = 원소 3개

[1] 3 5 7

In [5]:
seq(from=1, by=0.05, along=1:5) #along 으로 수열지정시 해당 수열에 따라 동일한 크기 벡터 생성

[1] 1.00 1.05 1.10 1.15 1.20

In [6]:
rep(c(1,2), times=2) #1과 2로 구성된 벡터를 2회 반복

[1] 1 2 1 2

In [7]:
rep(1:2, times=2) #1에서 2까지로 구성된 벡터를 2회 반복

[1] 1 2 1 2

In [8]:
rep(c(2,4), times=c(2,1)) #앞의 원소는 2회, 뒤의 원소는 1회 반복

[1] 2 2 4

In [9]:
rep(c(2,4), each=2) #앞, 뒤 모든 원소를 2회 반복

[1] 2 2 4 4

In [10]:
rep(c(2,4,8), length=5) #2,4,8로 구성된 벡터를 반복하되 생선되는 벡터의 크기를 5로 한정

[1] 2 4 8 2 4

#데이터의 편집
na.last=TRUE 라고 기본값으로 지정된 옵션의 의미는 만약 결측치 존재한다면 자료의 맨 끝에 위치하는 것으로 간주 decreasing=FALSE 오름차순을 기본으로 하라

In [11]:
v1<-c(11:20)
v1

[1] 11 12 13 14 15 16 17 18 19 20

In [12]:
v1[c(3,5)] #v1의 세번째와 다섯번째 값 출력

[1] 13 15

In [13]:
v1[v1>15] #v1의 원소 중 15보다 큰 값을 출력

[1] 16 17 18 19 20

In [14]:
v1[c(-2,-4)] #v1의 원소 중 두 번째와 네 번째 값을 삭제하고 출력 

[1] 11 13 15 16 17 18 19 20

In [15]:
v2 <-c(1:5)
v2

[1] 1 2 3 4 5

In [16]:
replace (v2,2,6) #v2의 두번째 원소 값을 6으로 변경

[1] 1 6 3 4 5

In [17]:
append(v2,8,after=5)#v2의 다섯 번째 값 다음에 8을 추가

[1] 1 2 3 4 5 8

In [18]:
v3 <-append(v2,8,after=5)
v3

[1] 1 2 3 4 5 8

#3을 세번 반복한 뒤 3에서 7까지 2만큼의 증가분으로 수열을 생성하고 이어서 rev()함수를 이용해서 3에서 7까지 이르는 크기 3인 벡터의 역순을 구해 연결한 뒤 4를 세 번 반복한 벡터를 덧붙임 + 여기다 sort 이용해서 오름차순 정렬, rank 함수를 통해 자료 순위 출력, order 함수 이용해 오름차순에 의한 자료의 위치 값 출력

In [19]:
rep(3,3) 
rev(seq(3,7,2))
rep(4,3)

[1] 3 3 3

[1] 7 5 3

[1] 4 4 4

In [22]:
x<-c(rep(3,3),seq(3,7,by=2),rev(seq(3,7,length=3)),rep(4,3))
x
sort(x)
rank(x) #자료의 순위 출력 3 다섯개가 5위까지 해당하는 값을 갖기 때문에 평균값 (1-5등까지 동률이니까 평균 3을 준다)
order(x) #원래 자료의 위치값 

[1] 3 3 3 3 5 7 7 5 3 4 4 4

[1] 3 3 3 3 3 4 4 4 5 5 7 7

[1]  3.0  3.0  3.0  3.0  9.5 11.5 11.5  9.5  3.0  7.0  7.0  7.0

[1]  1  2  3  4  9 10 11 12  5  8  6  7

In [23]:
vector("complex",5) #벡터로 초기화
logical(3) #logical 벡터로 초기화
numeric(4) #numeric 벡터로 초기화
complex(5) #complex 벡터로 초기화
character(6) #character 벡터로 초기화

[1] 0+0i 0+0i 0+0i 0+0i 0+0i

[1] FALSE FALSE FALSE

[1] 0 0 0 0

[1] 0+0i 0+0i 0+0i 0+0i 0+0i

[1] "" "" "" "" "" ""

#행렬

In [24]:
matr <-matrix(1:9,nrow=3)#3행 3열 행렬 생성
matr

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [25]:
length(matr)#원소 개수
mode(matr) #원소 형태
dim(matr) #행과 열의 개수

[1] 9

[1] "numeric"

[1] 3 3

#matrix(data,nrow=,ncol=,byrow=FALSE, dimnames=NULL)
#cbind(벡터1,벡터2) 또는 rbind(벡터1,벡터2)
#dim(x) <-c(행의 개수, 열의 개수)

In [27]:
r1<-c(1,2,3)
r2<-c(4,5,6)
r3<-c(7,8,9)
rbind(r1,r2,r3)

[,1] [,2] [,3]
r1 1    2    3   
r2 4    5    6   
r3 7    8    9

In [28]:
c1 <- c(1:3)
c2 <- c(4:6)
c3 <- c(7:9)
cbind(c1,c2,c3) #열을 기준으로 경합

c1 c2 c3
[1,] 1  4  7 
[2,] 2  5  8 
[3,] 3  6  9

In [30]:
m1 <- 1:9
dim(m1)<-c(3,3) #dim:차원 지정
m1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

#행렬의 연산 
[]를 이용하여 행렬의 일부 원소를 추출
apply(행렬, 조건,fun) 함수를 이용한 행 또는 열의 연산
sweep(행렬, 조건,stats, fun=) 함수를 이용한 연산

In [32]:
x1 <- 1:9
dim(x1) <-c(3,3)
x1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [33]:
mat <-matrix(c(1:9),ncol=3,byrow=T) #byrow=T 를 줌으로써 행 기준 3열의 행렬 생성 (디폴트는 열 방향)
mat

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [34]:
mat[1,] #1행의 값
mat[,2] #2열의 값
mat[mat[,3]>4,2] #3열에서 4보다 큰 행의 값 중 2열의 모든 값
mat[2,3] #2행 3열의 값 추출

[1] 1 2 3

[1] 2 5 8

[1] 5 8

[1] 6

In [39]:
height <-c(140, 155, 142, 175)
size.1 <- matrix(c(130,26,110,24,118,25,112,25), ncol=2, byrow=T,dimnames=list(c("Lee","Kim","Park","Choi"), c("Weight","Waist")))
size.1 <- cbind(size.1, height) #열 기준 결합

In [40]:
colmean <- apply(size.1,2,mean) #2: 열평균 계산
colmean

Weight  Waist height 
 117.5   25.0  153.0

In [41]:
rowmean <- apply(size.1,1,mean) #행평균 계산
rowmean

Lee       Kim      Park      Choi 
 98.66667  96.33333  95.00000 104.00000

In [42]:
colvar <- apply(size.1,2,var) #열의 분산값 계산
colvar

Weight       Waist      height 
 81.0000000   0.6666667 259.3333333

In [43]:
rowvar <- apply(size.1,1,var) #행의 분산값 계산
rowvar

Lee      Kim     Park     Choi 
3985.333 4430.333 3819.000 5673.000

In [44]:
sweep(size.1,2,colmean) #size 각 열의 값과 colmean 의 차 기본연산은 빼기로 되어 있음

Weight Waist height
Lee  12.5    1    -13   
Kim  -7.5   -1      2   
Park  0.5    0    -11   
Choi -5.5    0     22

In [46]:
sweep(size.1,1,rowmean) #size 각 행의 값과 rowmean 의 차

Weight   Waist     height  
Lee  31.33333 -72.66667 41.33333
Kim  13.66667 -72.33333 58.66667
Park 23.00000 -70.00000 47.00000
Choi  8.00000 -79.00000 71.00000

In [47]:
sweep(size.1,1,c(1,2,3,4), "+") #각 행의 값에 c(1,2,3,4)값을 더해줌

Weight Waist height
Lee  131    27    141   
Kim  112    26    157   
Park 121    28    145   
Choi 116    29    179

In [48]:
sweep(size.1,1,c(1,2,3,4),"-") #각 행에서 빼줌

Weight Waist height
Lee  129    25    139   
Kim  108    22    153   
Park 115    22    139   
Choi 108    21    171

행렬 연산 관련 함수 
t 전치행렬 t(a) %*$행렬 곱 crossprod t(A)%*%B outer(A,B) 외적 svd(A) singular value 분해 qr(A) QR 분해 solve(A,B) 방정식의 해 solve(A) 역행렬 eigen(A) 고유치와 고유벡터 chol(A) choleski 분해함수 

In [49]:
m1 <- matrix(1:4, nrow=2) 
m1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [51]:
m2 <- matrix(5:8, nrow=2)
m2

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [52]:
m1%*%m2

[,1] [,2]
[1,] 23   31  
[2,] 34   46

In [53]:
solve(m1) #역행렬

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [54]:
t(m1) #m1의 전치행렬 - 행과 열을 바꾼다 

[,1] [,2]
[1,] 1    2   
[2,] 3    4

#데이터구조(2)

In [ ]:
arr <- array(1:24, dim=c(3,3,2)) #mnatrix 에서는 행렬 숫자가 딱 맞아야 되는데 array 는 좀 더 융통성 있음 
arr
dimnames(arr) <- list(paste("row", c(1:3)),paste("col",c(1:3)),paste("ar",c(1:2)))#각 차원의 이름을 지정
arr 
length(arr) #자료 개수 확인
mode(arr) #각 차원 벡터의 크기
dimnames(arr) #각 차원 리스트의 이름 

배열은 행렬의 확장으로 기본적인 성질이 행렬과 유사 
array(data, dim=c(행 개수, 열 개수, 행렬 개수, dim.names=NULL)
dim(x) <-c(행의 개수, 열의 개수, 행렬의 개수)

In [73]:
array(1:6)

[1] 1 2 3 4 5 6

In [74]:
array(1:6, c(2,3))

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [76]:
array(1:8, c(2,2,2))
arr <- c(1:24) #이건 벡터 1차원 자료구조
dim(arr) <-c(3,4,2) #이건 배열이 됨 
arr

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

In [ ]:
ary1 <- array(1:8, dim=c(2,2,2))
ary2 <- array(8:1, dim=c(2,2,2))

In [ ]:
ary1 + ary2 #원소별 연산 
ary1 * ary2 #배열의 곱셈
ary1 %*% ary2 #두 배열 원소들의 곱의 합 행렬일 때와 배열일 때와 다르다 
ary1[,,1] # 배열 원소의 추출/삭제
ary1[1,1,]
ary1[1,,-2]

#리스트 - 서로 다른 형태의 데이터로 구성된 객체. length, mode, names

In [82]:
a <- 1:10
b <- 11:15
klist <- list(vec1=a, vec2=b, descrip="example")
length(klist) #배열 까지는 개별 원소 개수 list 에서는 component 개수 세개 매우 중요 
mode(klist)
names(klist)
klist

[1] 3

[1] "list"

[1] "vec1"    "vec2"    "descrip"

$vec1
 [1]  1  2  3  4  5  6  7  8  9 10

$vec2
[1] 11 12 13 14 15

$descrip
[1] "example"

In [81]:
clist <- list(a,b,"example")
length(clist)
mode(clist)
names(clist)
clist

[1] 3

[1] "list"

NULL

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
[1] 11 12 13 14 15

[[3]]
[1] "example"

In [83]:
list1 <- list("A", 1:8)
list1

[[1]]
[1] "A"

[[2]]
[1] 1 2 3 4 5 6 7 8

In [85]:
list1[[3]]<-list(c(T,F))
list1

[[1]]
[1] "A"

[[2]]
[1] 1 2 3 4 5 6 7 8

[[3]]
[[3]][[1]]
[1]  TRUE FALSE

In [87]:
list1[[2]][9]<-9 #두번째 성분에 원소 추가
list1

[[1]]
[1] "A"

[[2]]
[1] 1 2 3 4 5 6 7 8 9

[[3]]
[[3]][[1]]
[1]  TRUE FALSE

In [88]:
list1[3]<-NULL #세번째 성분 삭제
list1[[2]] <-list1[[2]][-9] #두번째 성분의 9번째 원소 삭제
list1

[[1]]
[1] "A"

[[2]]
[1] 1 2 3 4 5 6 7 8

In [89]:
a<-1:10
b<-11:15
nlist<-list(vec1=a,vec2=b,descrip="example")
nlist

$vec1
 [1]  1  2  3  4  5  6  7  8  9 10

$vec2
[1] 11 12 13 14 15

$descrip
[1] "example"

In [90]:
nlist[[2]][5]
nlist$vec2[c(2,3)] #vec2의 두번째와 세번째 원소 

[1] 15

[1] 12 13

#데이터프레임 - 형태가 일반화된 행렬. 하나의 객체에 여러 종류의 자료가 들어갈 수 있음. 각 열은 각각 변수와 대응. 분석이나 모형설정에 적합

In [95]:
d2 <- read.table("story.txt", row.names='num', header=T) #num은 데이터의 num이라는 변수가 행 이름임을 나타냄 
d2

name age sex
1 lee  55  m  
2 Park 47  F  
3 So   35  M  
4 Kim  26  F  
5 Yoon 29  M

In [96]:
char1 <- rep(LETTERS[1:3],c(2,2,1)) #abc 를 두개 두개 하나 반복하라
char1

[1] "A" "A" "B" "B" "C"

In [97]:
num1<-rep(1:3,c(2,2,1))
num1

[1] 1 1 2 2 3

In [98]:
test1<-data.frame(char1,num1)
test1

char1 num1
1 A     1   
2 A     1   
3 B     2   
4 B     2   
5 C     3

In [100]:
a1<-LETTERS[1:15]
a1
dim(a1)<-c(5,3)
a1

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O"

[,1] [,2] [,3]
[1,] A    F    K   
[2,] B    G    L   
[3,] C    H    M   
[4,] D    I    N   
[5,] E    J    O

In [101]:
test3<-as.data.frame(a1) #문자형 행렬을 데이터프레임으로 변경 - 열번호 행번호가 사라지고 변수명과 각 케이스로 변환 
test3

V1 V2 V3
1 A  F  K 
2 B  G  L 
3 C  H  M 
4 D  I  N 
5 E  J  O

In [102]:
cbind(test1,test3)

char1 num1 V1 V2 V3
1 A     1    A  F  K 
2 A     1    B  G  L 
3 B     2    C  H  M 
4 B     2    D  I  N 
5 C     3    E  J  O

In [103]:
char1 <- rep(LETTERS[1:3],c(1,2,2))
char1

[1] "A" "B" "B" "C" "C"

In [105]:
num1 <-rep(1:3,c(1,1,3))
num1
test4<-data.frame(char1,num1)
test4

[1] 1 2 3 3 3

char1 num1
1 A     1   
2 B     2   
3 B     3   
4 C     3   
5 C     3

In [106]:
rbind(test1,test4) #아래로 합친 형태

char1 num1
1  A     1   
2  A     1   
3  B     2   
4  B     2   
5  C     3   
6  A     1   
7  B     2   
8  B     3   
9  C     3   
10 C     3

In [107]:
merge(test1,test4) #같은 변수에 대해 한번만 출력. 처음의 변수에 대해 알파벳 순서로 정렬이 되고 나머지 변수들이 옆으로 나열

char1 num1
1 A     1   
2 A     1   
3 B     2   
4 B     2   
5 C     3   
6 C     3